### ISSUE TITLE
わいわいswiftc #18

### ISSUE THREAD

**Issue by giginet** [waiwai-swiftc/events#1]
## 日時

2/19

## 場所

クックパッド株式会社

## connpass

[わいわいswiftc #18 - connpass](https://iosdiscord.connpass.com/event/164900/)

## コンテンツ

- @sidepelican Generics最適化
- @sonsongithub LLVMでのJIT実装

**Comment by giginet** [comment]
日程決めます

**Comment by sonsongithub** [comment]
llvmの発表でもいいなら，llvmでJIT実行するコードの解説とかします．

**Comment by giginet** [comment]
2/21(Fri.)クックパッド開催で進めています

**Comment by giginet** [comment]
2/21、型システム祭りとぶつかるとのことで別の日にします

@sidepelican @sonsongithub 2/19(Wed.)はご都合如何でしょうか？

**Comment by sidepelican** [comment]
大丈夫です！

**Comment by sonsongithub** [comment]
ええよ

**Comment by giginet** [comment]
2/19水曜日に確定しました。conpass準備します

**Comment by giginet** [comment]
こちら、コロナウイルスの流行で会場提供が難しくなったため、一度中止させていただきます。
次回以降の開催予定は未定です。ご迷惑をおかけ致しますが、よろしくお願いします。

https://iosdiscord.connpass.com/event/164900/
