### ISSUE TITLE
01/24 わいわいswiftc #32

### ISSUE THREAD

**Issue by tarunon** [waiwai-swiftc/events#21]
## 日時
  
01/24 (木曜日)

- [x] 登壇予定者全員が参加できるか、登壇準備ができるか確認する
- [x] 参加者が被りそうな勉強会とぶつかっていないか、イベントカレンダーで確認する https://connpass.com/calendar/

## connpass

[わいわいswiftc #32 - connpass](https://connpass.com/event/235947/edit/)

## コンテンツ

- @d-date SPMで何か
~

**Comment by freddi-kit** [comment]
資料は次回登壇時に提出でもよさそうだしCloseします
