### ISSUE TITLE
04/25 わいわいswiftc #35

### ISSUE THREAD

**Issue by sidepelican** [waiwai-swiftc/events#25]
## 日時
  
04/25 (月曜日)

- [x] 登壇予定者全員が参加できるか、登壇準備ができるか確認する
- [x] 参加者が被りそうな勉強会とぶつかっていないか、イベントカレンダーで確認する https://connpass.com/calendar/
- [x] Discordのイベント機能でスケジュールしておく　（チャンネル一覧の一番上にある Event から Create Event を選択）

## 場所

- オンライン
  - [Discord](https://swift-developers-japan.github.io/) の `waiwai-swiftc` チャンネル

## connpass

[わいわいswiftc #35 - connpass](https://iosdiscord.connpass.com/event/243040/)

## コンテンツ

- @omochimetaru SwiftSyntaxをうまく使おう
- @iceman5499 夢が広がる！コード生成でどこでもSwift

**Comment by freddi-kit** [comment]
connpassのカレンダー的にイベント少ないので4/25(月)が次回良さそう

**Comment by sidepelican** [comment]
実はconnpassをその日付ですでに作ってあったけど、そこから先を放置していた・・・

**Comment by sidepelican** [comment]
運営者権限でこっそり発表タイトルを変えた

**Comment by sidepelican** [comment]
開催完了した
