### ISSUE TITLE
4/20 わいわいswiftc #19 オンライン

### ISSUE THREAD

**Issue by giginet** [waiwai-swiftc/events#4]
## 日時
  
4/20 (Mon.) 19:30~

## 場所

Swift Discord Go Live
(参加方法準備中）

## connpass

https://connpass.com/event/171835

## コンテンツ

- @sidepelican Generics最適化
- @sonsongithub LLVMでのJIT実装
- @omochi 

#1 がcovid19の影響で中止になったので代わりにオンライン開催をします

**Comment by giginet** [comment]
また型システム祭りと被ってしまったので日程変えます……

**Comment by freddi-kit** [comment]
@giginet 
https://connpass.com/calendar/?ym=202004 見る限りだと20とか良いかもですね
金曜がよかったら５月とかでも良さげ

**Comment by omochi** [comment]
hook test

**Comment by giginet** [comment]
4/20(Mon.) 19:30から確定しました。イベントページも公開しています。

https://connpass.com/event/171835

**Comment by giginet** [comment]
参加してくれた方ありがとうございました。 # 20 (#5) もよろしくお願いします
