### ISSUE TITLE
5/22 わいわいswiftc #20

### ISSUE THREAD

**Issue by giginet** [waiwai-swiftc/events#5]
## 日時
  
5/22 (金曜日)

## 場所

Discord

## connpass

[わいわいswiftc #20 オンライン - connpass](https://iosdiscord.connpass.com/event/174409/)

## コンテンツ

- @freddi-kit 
- @omochi

**Comment by omochi** [comment]
「CSFixとラベルマッチ」
で話します

**Comment by giginet** [comment]
@freddi-kit 5/22(Fri.)を目安にやっていこうと思ってるが日程大丈夫でしょうか？

**Comment by freddi-kit** [comment]
未来の自分に任せるので大丈夫でっす！

**Comment by giginet** [comment]
公開しました！！！

[わいわいswiftc #20 オンライン - connpass](https://iosdiscord.connpass.com/event/174409/)

**Comment by freddi-kit** [comment]
mapのoptimizationの話か、DCEで使われているある関数の実装を見るやつやるかなあ。今週までにネタ決めます

**Comment by freddi-kit** [comment]
正確に言えば、Swiftコンパイラの`mayHaveSideEffects`関数の実装の話か`map`のoptimizationのはなしします

**Comment by freddi-kit** [comment]
開催お疲れさまでした！

**Comment by giginet** [comment]
スライドconnpassに載せないとな

**Comment by freddi-kit** [comment]
自分のやつは載せたのですが、おもちさんのスライドがどこになるかわかんないです

**Comment by freddi-kit** [comment]
全部のせておきました
